#!/usr/bin/python3
from app import app, db

#f = open('shell_script','r', encoding="utf-8")
#the_file = f.read().split('\n')
#f.close()
#
#print(the_file)


if __name__=='__main__':
  app.run(host='0.0.0.0', port=8088)


